repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.5
    hooks:
      - id: typos
        verbose: true
        args:
          - "--config"
          - ".github/typos.toml"
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: local
    hooks:
      - id: kebab-case-files-only
        name: kebab-case files only
        entry: filenames must be kebab-case only
        language: fail
        files: '[^a-z0-9.\/\[\]@-]'
        exclude: |
          (?x)^(
            .github/.*|
            .git/COMMIT_EDITMSG|
            LICENSE|
            README.md
          )$
